import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { AnimatedBackground } from "@/components/animated-background";
import { AuthProvider } from "@/context/auth-context";
import { Toaster } from "sonner";
import { ApiStatus } from "@/components/api-status";



const spaceMono = localFont({
  src: [
    {
      path: "./fonts/SpaceMono-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/SpaceMono-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-space-mono",
  display: "swap",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${spaceMono.className} ${spaceMono.variable} antialiased`}
      >
        <ApiStatus />
        <AnimatedBackground />
        <AuthProvider>

        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          disableTransitionOnChange
          >
          {children}
        </ThemeProvider>
          </AuthProvider>
          <Toaster visibleToasts={5} position={"top-right"}
          // richColors
          closeButton
          toastOptions={{
            unstyled: true,
            classNames: {
              toast: "glass w-100 min-h-20 p-4 rounded-lg flex items-center justify-center gap-2",
              closeButton: "absolute top-0.5 right-0.5 rounded-full"
            }
          }}
          />
      </body>
    </html>
  );
}
